### ISSUE TITLE
Only first nodepool is created

### ISSUE THREAD

**Issue by exocode** [crossplane-contrib/provider-civo#13]
Just wanna drop some bugs in the old year, so we can "slip clean" into the new one :-) 

I still have some troubles with my manifest:

1. Only the **very first nodepool** is created
2. How to assign labels to cluster?

I have this manifest, try for yourself please:

```yaml
kind: CivoKubernetes
apiVersion: cluster.civo.crossplane.io/v1alpha1
metadata:
  name: production-crossplane
spec:
  name: production-crossplane
  pools:
    - id: "master-pool"
      count: 3
      size: g3.k3s.small
    - id: "worker-pool" # not created
      count: 3
      size: g3.k3s.medium
    - id: "service-pool" # not created
      count: 1
      size: g3.k3s.large
  applications:
    - "metrics-server"
    - "argo-cd"
  connectionDetails:
    connectionSecretNamePrefix: "cluster-details"
    connectionSecretNamespace: "production"
  providerConfigRef:
    name: civo-provider
```

But only first nodepool "master-pool" is created. all others are ignored:

<img width="1408" alt="Bildschirmfoto 2021-12-31 um 13 01 34" src="https://user-images.githubusercontent.com/1597621/147823245-39e13857-e342-49bd-be2d-1e4e72f77d9f.png">

I have enough ressource quota:

<img width="755" alt="Bildschirmfoto 2021-12-31 um 13 04 08" src="https://user-images.githubusercontent.com/1597621/147823268-df243b8b-a650-4977-a405-03c77c12e2e6.png">
