### ISSUE TITLE
default Marketplace applications colliding with my requirements

### ISSUE THREAD

**Issue by exocode** [crossplane-contrib/provider-civo#19]
I am using ArgoCD to apply my manifests. One of my apps is a custom `ingress-nginx-controller` (not the one of marketplace).

The "default" apps of Civo makes it impossible to deploy my own "traefik" or "ingress-nginx-ingress".

### What happened?

When I create a cluster with Civo-Provider (or recreate it by deleting it in the Civo UI) 
autmatically two "apps" of the Civo marketplace are automatically enabled:
- metrics-server
- traefik

I am not able to disable them. 

### What I tried so far:

- I tried to omit **any** `spec.applications`
- I tried to add any `spec.applications` (eg: metrics-server) 

Bot approaches are automatically deploys the "Marketplace" applications. So there is no chance to disable them. This is only possible when creating cluster in the UI.

### How can we reproduce it?

Apply on your cluster
```yaml
kind: CivoKubernetes
apiVersion: cluster.civo.crossplane.io/v1alpha1
metadata:
  name: vonhier-production
  labels:
    argocd.civo.crossplane.io/cluster: vonhier-production
spec:
  name: vonhier-production
  pools:
    - id: "app-pool"
      count: 3
      size: g3.k3s.medium
    - id: "data-pool"
      count: 1
      size: g3.k3s.medium
  applications:  # with or without spec.applications: traefik and metrics-server are always deployed
    - "ANY_APPLICATION"
  connectionDetails:
    connectionSecretNamePrefix: "kubeconfig"
    connectionSecretNamespace: "default"
  providerConfigRef:
    name: civo-provider-config
```

### What environment did it happen in?
Crossplane version:  crossplane/crossplane:v1.5.1
