### ISSUE TITLE
unable to install civo provider 

### ISSUE THREAD

**Issue by jebinjeb** [crossplane-contrib/provider-civo#23]
### What environment did it happen in?
Crossplane version: 1.7.0 & 1.6

**Comment by jebinjeb** [comment]
Events:
  Type     Reason         Age                 From                                 Message
  ----     ------         ----                ----                                 -------
  Warning  UnpackPackage  45s (x502 over 8h)  packages/provider.pkg.crossplane.io  cannot unpack package: failed to fetch package digest from remote: HEAD https://index.docker.io/v2/crossplane/provider-civo/manifests/master: unexpected status code 404 Not Found (HEAD responses have no body, use GET for details)

**Comment by hopkinsjason** [comment]
Worked for me if I added this resource:

```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-civo
spec:
  package: xpkg.upbound.io/civo/provider-civo:v0.1
```

The documentation is wrong by the look of it.
